// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdggndkvpbclskslrskc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZ2duZGt2cGJjbHNrc2xyc2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzY3NTMsImV4cCI6MjA2OTY1Mjc1M30.4Xey8aF1qCmLIopm72Mn3D_mrFM5Nui-Z9vwOeQfn-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});